### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by nikhilravikrishnan** [ijc8/MUSI-6106#1]
Set up dependencies for the project

JUCE - https://docs.juce.com/master/tutorial_new_projucer_project.html

Stockfish - https://github.com/official-stockfish/Stockfish

**Comment by ijc8** [comment]
I propose we all try to get [this example application](https://docs.juce.com/master/tutorial_sine_synth.html) (which includes a GUI and audio) compiled and running on our machines by Wednesday.
